using System.IO;
using Keepfall.Economy;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace Keepfall.EditorTools
{
    /// <summary>
    /// Editor entry points for the <c>milestone/01-economy</c> deliverable: an editor-playable
    /// economic loop end-to-end (source-of-truth §13). Rather than ship a hand-authored
    /// <c>.unity</c> file, these menu items let Unity's own serializer build the scene — so it is
    /// correct by construction — and let you drop the demo into any scene. The loop logic lives in
    /// <see cref="EconomyLoopDriver"/>; this is just the editor on-ramp.
    /// <para>Menu: <b>Keepfall ▸ Economy</b>.</para>
    /// </summary>
    public static class EconomyDemoMenu
    {
        private const string SceneDir = "Assets/Scenes";
        private const string ScenePath = SceneDir + "/EconomyLoop.unity";
        private const string BootstrapName = "EconomyBootstrap";

        /// <summary>
        /// Spawns the <see cref="EconomyLoopDriver"/> bootstrap into the open scene. Press Play and
        /// watch the Console: the loop seeds a save, grants a tile from a "win", accrues Stone
        /// against the wall clock, and exposes claim/unlock actions on the component's context menu.
        /// Shortcut: Ctrl/Cmd+Shift+E.
        /// </summary>
        [MenuItem("Keepfall/Economy/Spawn Economy Loop Demo %#e")]
        public static void SpawnDemo()
        {
            EconomyLoopDriver existing = Object.FindFirstObjectByType<EconomyLoopDriver>();
            if (existing != null)
            {
                Selection.activeGameObject = existing.gameObject;
                Debug.Log("[Keepfall] EconomyBootstrap already present. Press Play to run the loop.");
                return;
            }

            var go = new GameObject(BootstrapName);
            go.AddComponent<EconomyLoopDriver>();
            Undo.RegisterCreatedObjectUndo(go, "Spawn Economy Loop Demo");
            Selection.activeGameObject = go;
            Debug.Log("[Keepfall] Spawned EconomyBootstrap. Press Play; the Console prints each step.");
        }

        /// <summary>
        /// Creates and saves <c>Assets/Scenes/EconomyLoop.unity</c> (default scene objects +
        /// the bootstrap), generated by Unity so the asset is always valid. Open it and press Play.
        /// </summary>
        [MenuItem("Keepfall/Economy/Create Economy Loop Scene")]
        public static void CreateScene()
        {
            UnityEngine.SceneManagement.Scene scene = EditorSceneManager.NewScene(
                NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);

            var go = new GameObject(BootstrapName);
            go.AddComponent<EconomyLoopDriver>();

            Directory.CreateDirectory(SceneDir);
            bool saved = EditorSceneManager.SaveScene(scene, ScenePath);
            if (saved)
            {
                AssetDatabase.Refresh();
                Debug.Log($"[Keepfall] Created {ScenePath}. Open it and press Play to run the loop.");
            }
            else
            {
                Debug.LogError($"[Keepfall] Could not save {ScenePath}.");
            }
        }
    }
}
